msktutil/msktutil

krb5wrap.cpp, krb5wrap.h, msktkrb5.cpp, msktutil.cpp, msktutil.h
Introducing a "C" krb5_error_exit() and refatcoring error_exit() infrastructure from msktutil
Should be tested. But compiles clean with gcc-7 on macosx (aside from deprecations at macosx level)
=> Do not throw exceptions within destructor

msktkrb5.cpp, msktname.cpp, msktutil.cpp, msktutil.h
msktutil adds a default keytab entry for `host/<sAMAccountName>` while `host/<shorthostname>` was actually intended. Commonly, both names match, but problems will arise if they don't: The generated SPN is actually invalid because it is unknown in AD, whereas the valid SPN based on the short hostname may be required, but is missing. This set of changes corrects this, and cleans up a few of the touched code paths.
=> Fix creation of SPNs for short hostnames

Makefile.in, msktname.cpp, msktname.h, msktutil.h
When trying to deduce the domain controller to use from DNS, our current scheme just chooses one and sticks with it. If this domain controller is not fully operational for some reason, msktutil will fail, even if there were other, working domain controllers in the DNS response. The changes in this PR clean up and refactor the code doing the DNS handling, and add a validation step to make sure we only pick a domain controller that's operational.
=> Improve robustness to errors in DNS entries

msktname.cpp
Ensure SRV queries will only return actual domain controllers by using the
special subdomain "dc._msdcs." (cf.
https://technet.microsoft.com/en-us/library/cc961719.aspx).
=> msktname.cpp: fix SRV lookups for AD DCs (fixes #84)

msktkrb5.cpp
The access() checks introduced in c1efe42019be5ebcd42aadcc648ac3948a4f88ce require a valid flags->keytab_file, which was unset if using default keytab locations. This change initializes flags->keytab_file in these cases as well.
=> msktkrb5.cpp: make sure keytab_file is always set (fixes #76)

krb5wrap.cpp, krb5wrap.h, msktkrb5.cpp, msktutil.h
Use timestamps for sorting of entries, and only use equality comparisons with
kvnos to avoid problems if kvnos wrap around. Introduce new class
`KRB5KeytabEntry` in favour of `KRB5Keyblock` to streamline code.
closes: #69 -- `add_principal_keytab`: bogus kvno comparisons
closes: #85 -- Failure to write keytab entries for more than one principal
=> msktkrb5: re-implement keytab pruning logic

msktutil.cpp
Initializer for this member was missing in the default ctor.
Thanks, valgrind!
=> msktutil.cpp: initialize dont_update_dnshostname flag

krb5wrap.cpp
Before adding a new entry, we always try to remove any entry for the same
combination of principal/kvno/enctype. (Fixes: #92)
=> krb5wrap.cpp: avoid duplicate entries in keytab

msktname.cpp, msktname.h
Commit 20adbc14fccaab634e2b1273cf0c3a7fffdf536b introduced an incorrect syntax for the DnsSrvHost constructor when using libudns. Change to something that actually resembles C++.
(Fixes: #93)
=> msktname.h: fix ctor syntax for DnsSrvHost with libudns

msktutil.M, msktutil.cpp, msktutil.h
This adds mode name consistency with other modes like create or update.
=> Rename delete-account mode to delete mode

msktldap.cpp, msktutil.M, msktutil.cpp, msktutil.h
I was missing an --enable option to enable an account that was disabled when leaving a domain before. 
During the join operation the account would be enabled so this is not useful for normal operations. 
What I do is for automated windows deployment, instead of joining using an admin account and having that one password in unattended.xml for everyone to grab, I join computers using their own machine account. The password is downloaded from a web service that runs msktutil to set it.  To be able to authenticate with the machine account, it must be enabled.
The change is simple and you already have the necessary infrastructure in the code.
=> Add --enable command line option to enable the account 

Makefile.in
Man page does not require execute permission. Setting
sane modes keeps rpmlint happy. (Fixes: #113)
=> Makefile.in: explicitly set permissions on install

Makefile.in
When configure is running from an autoconf V2.69 generated source a Warning is displayed:
> config.status: WARNING:  '../msktutil/Makefile.in' seems to ignore the --datarootdir setting
Pull request is silencing this warning.
See https://www.gnu.org/software/autoconf/manual/autoconf.html#Changed-Directory-Variables
=> Silence warning from autotools

msktpass.cpp, msktutil.M, msktutil.cpp, msktutil.h, samba-password-command.sh
Following the discussion at: https://github.com/msktutil/msktutil/issues/124 here is proposed implementation of using external command instead of 'net' to set samba machine password in secrets.tdb
This PR also includes an example samba 4.7 workaround script which can be used as such command.
=> Implements --use-samba-cmd option

ldapconnection.cpp, ldapconnection.h, msktutil.M, msktutil.cpp, msktutil.h
There are two motivations for this:
1. There is good reason to change the preferred mechanism from GSSAPI to GSS-SPNEGO. (See below.)
2. Allowing the candidate mechanism list to be overridden on the command line permits both easily restoring the old behavior of using GSSAPI, and potentially using newer mechanisms in the future without needing to rebuild msktutil.
Previously, the `ldap_sasl_interactive_bind_s()` call hardcoded the GSSAPI mechanism. While this mechanism should be supported by any modern Active Directory Domain Controller, most DCs also support the newer GSS-SPNEGO mechanism.
As of August 2019, Microsoft recommends enabling LDAP channel binding and LDAP signing:
https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/ldap-channel-binding-and-ldap-signing-requi …
=> Permit specifying candidate SASL mechanisms for the LDAP bind.

msktkrb5.cpp
This closes #158 and closes #160
=> Print effectively supported encryption types when constructing a keytab

msktldap.cpp, msktutil.cpp, msktutil.h
* Move all default values to a compile time macro: DEFAULT_MS_KERB_ENCTYPES
and use macro throughout
* Introduce macro ALL_MS_KERB_ENCTYPES for all supported encryption types
* Introduce macro MS_KERB_DES_ENCTYPES for all DES-based encryption types
* Invert logic to set DES only if it requested via command line
=> Clean up MS Kerberos encryption types (#157)

msktpass.cpp
Consumers of oldPwdLastSet have been removed in
bb40b477bb5fda9196c09507f2e87377fe48a218, so we can safely get rid of the
calls to ldap_get_pwdLastSet() that initializes it.
=> msktpass: remove stray LDAP calls (#180)

msktutil.cpp
No need to pass option argument, and static strings through format expansion.
Avoids potential crashes, and keeps CodeQL checks happy. Use standard string
comparison instead. Simplify code by pulling flags assignment out of helper
function, and rename function accordingly.
=> Clean up --remove-enctype option parsing

configure.ac
If the ns_initparse() function is contained in libc, like on FreeBSD the marco
for config.h was not set, therefore SRV RR queries were not available on
FreeBSD.
=> Fix ns_initparse() detection in libc for config.h

configure.ac, krb5wrap.cpp
We need to determine salt values based on the heuristics described in
windows-salt.txt. This may fail in some corner cases, and might break
completely in future versions of Active Directory, as the KDC is not
bound to follow a certain salt scheme. Recent MIT Kerberos (since
v1.17) allows to query the KDC for the proper salt value. We try to
make use of the interface if available, and fall back to the heuristics
in case of any failure.
Previously, the following test cases yielded invalid keytab entries
because the heurisic would derive an incorrect salt, based on the
sAMAccountName rather than the UPN. With this changeset in place,
a working keytab is created:
% kinit Administrator
% msktutil create --use-service-account \
--service HTTP/foo \
--account-name foo \
--upn HTTP/foo \
--keytab …
=> addEntry: try to use KDC-supplied salt info

msktkrb5.cpp, msktutil.M, msktutil.cpp, msktutil.h
msktutil --create ... without --service and without --use-service-account
should create a machine account with the following SPNs:
host/FQDN
host/shortname
This is what `setspn -R` is doing and what other "domain join" tools are doing.
Keytab entries are already created that way
With --service ... only the specified SPNs will be registered.
=> Consistent creation of SPNs

.github/workflows/msktutil.yml
On latest Fedora, some tools like libtool and krb5-config add a reference to
/usr/lib/rpm/redhat/redhat-annobin-cc1 to the generated compiler or linker
flags. Install package redhat-rpm-config to make sure this file is available
in our build environment.
=> Add missing dependency to fix fedora auto-build

.github/workflows/msktutil-freebsd.yml
Use fixed MacOS version dependency as per docs for latest version v0.1.5 of
freebsd-vm action (cf. also vmactions/freebsd-vm#38).
=> Update FreeBSD auto-build action to latest version

Makefile.in, configure.ac, msktutil.1.in
Custom sed rules in Makefile just replicate functionality that is already
present in configure itself.
=> Create man page from configure

krb5wrap.cpp, ldapconnection.cpp, msktconf.cpp, msktkrb5.cpp, msktldap.cpp, msktname.cpp, msktpass.cpp, msktutil.cpp, msktutil.h
* Highlight an error message instead of hiding in parentheses
* Capitalize start verbose messages
* Improve language style
* Clean up naming inconsistencies
* Use consistently colons as param value separator
* Denote UPNs, SPNs and SAM Account Names as such
* Capitalize after colon only if it is a full sentence or a paragraph
This closes #74 and closes #173
=> Apply a consistent formatting of messages and principals (#74, #173)

.github/workflows/msktutil.yml
Drop obsolete DockerHub-hosted images. Switch to current registry, and
stream-based images instead. Add CentOS 9 Stream to test matrix.
=> Fix and update CentOS autobuilds

configure.ac
We directly call function `error_message()` from
`libcom_err`, and therefore have to explicitly link the msktutil binary to it. This used to work because `krb5-config --libs` always included the necessary `-lcom_err`, but for dynamic linking, recent versions started to omit transitive dependencies, and merely return the minimal `-lkrb5` instead.
The explicit check for `libcom_err` was removed in 189f8b356ab78936cbfad2b1d4d827cdc0028341 as part of Solaris-related fixes. However, this part of the
commit is dubious because the check itself looks
correct and required. It is unclear why Solaris builds would break, but in any case, a different fix is
appropriate here.
This change reverts a part of commit 189f8b356ab78936cbfad2b1d4d827cdc0028341. It addresses a build problem discussed as part of …
=> configure.ac: fix linking with minimal LIBS

configure.ac
In order to distinguish between Heimdal and MIT, we used to check if some Heimdal-specific headers are present on the build system. Some distros allow both implementations to be installed in parallel, though, so this heuristic becomes fragile. Recent krb5-config supports the --vendor option, which provides a more reliable check. Fall back to the old method if no vendor is reported.
=> configure.ac: more robust krb5 autodetection

.github/workflows/msktutil-archs.yml, .github/workflows/msktutil-freebsd.yml, .github/workflows/msktutil-macos.yml, .github/workflows/msktutil-solaris.yml, .github/workflows/msktutil.yml
Extend CI tests to cover builds on UBI9 (RHEL9) and Solaris, and - barring a proper testsuite - add a minimalist runtime check of the resulting binary after each build.
=> CI enhancements
